import type { Metadata } from 'next';
import { profile } from '@/data/site';

/**
 * Per-page metadata with a canonical URL and matching Open Graph/Twitter fields.
 * Nested metadata objects replace (not merge with) the root layout's, so each page
 * sets them in full here.
 */
export function pageMetadata({
  title,
  description,
  path,
  absolute = false,
}: {
  title: string;
  description: string;
  path: string;
  /** Use `title` as-is instead of appending the site name. */
  absolute?: boolean;
}): Metadata {
  const fullTitle = absolute ? title : `${title} · ${profile.name}`;
  // A page-level openGraph object replaces the root one, including the image
  // generated by app/opengraph-image.tsx, so point back at it explicitly.
  const image = { url: '/opengraph-image', width: 1200, height: 630, alt: `${profile.name}, ${profile.role}` };
  return {
    title: absolute ? { absolute: title } : title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: 'website',
      siteName: profile.name,
      title: fullTitle,
      description,
      url: path,
      images: [image],
    },
    twitter: {
      card: 'summary_large_image',
      title: fullTitle,
      description,
      images: [image.url],
    },
  };
}
